openapi: 3.0.3
info:
  title: Domain
  description: Create subdomain to receive api data.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: https://domain.test/api/v1
    description: SandBox
  - url: https://domain.com/api/v1
    description: Production
tags:
  - name: users
    description: Resources for users
  - name: token
    description: Resources for token of users
  - name: domain
    description: Resources for domains
  - name: app
    description: Resources for check application
paths:
  /health:
    get:
      tags:
        - app
      description: Check if application is running
      responses:
        '200':
          description: Response with case of success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /users:
    post:
      tags:
        - users
      description: Creates a invoice by payment type
      parameters:
        - name: Authorization
          in: header
          description: |-
            Access token generated by the system administrator.
            Ex: Bearer [TOKEN]
          required: true
          schema:
            type: string
      requestBody:
        description: Create a invoice by payment type
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoices'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '500':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationException'
      security:
        - BearerAuth: []
  /tokens:
    post:
      tags:
        - token
      description: Refund invoice by identification
      parameters:
        - name: Authorization
          in: header
          description: |-
            Access token generated by the system administrator.
            Ex: Bearer [TOKEN]
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
      security:
        - BearerAuth: []
  /domains:
    post:
      tags:
        - domain
      description: Creates a invoice by payment type
      parameters:
        - name: Authorization
          in: header
          description: |-
            Access token generated by the system administrator.
            Ex: Bearer [TOKEN]
          required: true
          schema:
            type: string
      requestBody:
        description: Create a invoice by payment type
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoices'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '500':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationException'
      security:
        - BearerAuth: []
components:
  schemas:
    HealthResponse:
      properties:
        finishedAt:
          type: integer
          example: 1672754242
        checkResults:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Enviroment'
    Enviroment:
      type: object
      properties:
        name: 
          type: string
          example: Environment
        label:
          type: string
          example: Environment
        notificationMessage: 
          type: string
          example: The environment was expected to be `production`, but actually was `local`
        shortSummary: 
          type: string
          example: local
        status: 
          type: string
          example: failed
        meta:
          type: object
          properties:
            actual:
              type: string 
              example: local
            expected:
              type: string
              example: production
    InvoiceBase:
      required:
        - description
        - amount
        - payment_method
        - source
        - ref
        - items
        - payer
        - payments_settings
      type: object
      properties:
        description:
          type: string
          minLength: 1
          maxLength: 255
          example: doguue
        amount:
          type: integer
          format: int64
          example: 1000
          minimum: 1000
        payment_method:
          type: string
          description: type of payment
          enum:
            - credit_card
            - pix
            - boleto
            - credit_smart
        installments:
          type: integer
          example: 1
          minimum: 1
          maximum: 12
        source:
          description: request origin system
          type: string
          enum:
            - link
            - braip
        ref:
          type: string
          example: product-code
          maxLength: 255
        interest_amount:
          type: integer
          example: 100
        shipping_costs:
          type: integer
          example: 890
        discount_amount:
          type: integer
          example: 250
        payer:
          $ref: '#/components/schemas/PayerFields'
        items:
          type: array
          items:
            properties:
              ref:
                type: string
                description: Another reference
                example: item-code
    PayerFields:
      required:
        - name
        - document
        - email
        - phone
      properties:
        name:
          type: string
          example: Jhon Doe
        document:
          type: string
          description: cpf or cpnj of buyer
          example: '123456789'
        email:
          type: string
          example: client@email.com
        phone:
          type: string
          example: 3388888888
        nationality:
          type: string
          example: Brazil
        address:
          type: object
          description: Payer address information
          properties:
            street:
              type: string
              maxLength: 255
              example: Industrial Avenue
            number:
              type: string
              example: 1220
            complement:
              type: string
              maxLength: 255
              example: Braip
            district:
              type: string
              maxLength: 255
              example: Industrial District
            postal_code:
              type: string
              maxLength: 255
              example: 35010234
            city:
              type: string
              maxLength: 255
              example: Valadares Governor
            state:
              type: string
              maxLength: 255
              example: Minas Gerais
            state_code:
              type: string
              maxLength: 2
              example: MG
            country:
              type: string
              maxLength: 255
              example: Brazil
    Invoices:
      type: object
      allOf:
        - $ref: '#/components/schemas/InvoiceBase'
        - $ref: '#/components/schemas/PaymentsSettings'
    PaymentsSettings:
      properties:
        payments_settings:
          oneOf:
            - $ref: '#/components/schemas/CreditCard'
            - $ref: '#/components/schemas/Pix'
            - $ref: '#/components/schemas/Boleto'
    CreditCard:
      description: Fields for the credit card payment type, all are mandatory in the request.
      properties:
        credit_card:
          required:
            - number
            - holder_name
            - expiration_month
            - expiration_year
            - installments
          type: object
          properties:
            number:
              type: string
              example: 34238947728025430
            holder_name:
              type: string
              example: Jhon Doe
            expiration_month:
              type: string
              example: 10
            expiration_year:
              type: string
              example: 2022
            installments:
              type: integer
              minimum: 1
              maximum: 12
              example: 1
            metadata:
              $ref: '#/components/schemas/MetadataCreditCard'
    Pix:
      description: Fields for the pix payment type, all are mandatory in the request.
      properties:
        pix:
          type: object
          properties:
            due_date:
              type: string
              example: '2023-12-13T00:00:00.000Z'
    Boleto:
      description: Fields for the boleto payment type, all are mandatory in the request.
      properties:
        boleto:
          type: object
          properties:
            due_date:
              type: string
              example: '2023-12-13T00:00:00.000Z'
            with_pix:
              type: boolean
              enum:
                - false
                - true
            metadata:
              $ref: '#/components/schemas/MetadataBoleto'
    MetadataCreditCard:
      type: object
      description: Fields for the type of credit card payment when performing fraud analysis.
      properties:
        quantity:
          type: integer
          example: 1
        ip_address:
          type: string
          example: 127.0.0.1
        fingerprint:
          type: string
          example: 2179423m001m10rm178365873467
        product_hash:
          type: string
          example: kin23o4n
        product_name:
          type: string
          example: Sky Window
        product_format:
          type: string
          enum:
            - FISICO
            - INFOPRODUTO
        product_created_at:
          type: string
          example: '2020-12-01T00:00:00.000Z'
        product_category:
          type: string
          example: general
        producer_hash:
          type: string
          example: 0umin23o4n
        producer_name:
          type: string
          example: Jhon Doe
        producer_phone:
          type: string
          example: 3399999999
        producer_document:
          type: string
          description: Cpf or Cnpj
          example: 15010885050
        producer_created_at:
          type: string
          example: '2019-07-01T00:00:00.000Z'
        affiliate_hash:
          type: string
          example: msn2974n
        affiliate_name:
          type: string
          example: Abigail M
        affiliate_phone:
          type: string
          example: 3399999999
        affiliate_document:
          type: string
          description: Cpf or Cnpj
          example: 15010885050
        affiliate_created_at:
          type: string
          example: '2020-12-01T00:00:00.000Z'
    MetadataBoleto:
      type: object
      description: Field with additional information for generating a boleto.
      properties:
        final_beneficiary_name:
          type: string
          example: Dom Ruan
        final_beneficiary_fantasy_name:
          type: string
          example: Ops Blank
        final_beneficiary_document:
          type: string
          description: Cpf or Cnpj
          example: 15010885050
    Success:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              example: 22a3129e-9ebd-4955-b160-376befc33d34
            status:
              type: string
              enum:
                - pending
                - paid
                - canceled
                - refused
                - refunded
                - refunding
                - charged_back
                - in_mediation
                - in_process
                - partially_paid
                - delayed
            payment_method:
              type: string
              enum:
                - credit_card
                - pix
                - boleto
                - credit_smart
            amount:
              type: number
              example: 1000
            status_detail:
              type: string
              example: 'null'
            payment_details:
              oneOf:
                - $ref: '#/components/schemas/DetailsCard'
                - $ref: '#/components/schemas/DetailsPix'
                - $ref: '#/components/schemas/DetailsBoleto'
    DetailsCard:
      description: response of details card
      properties:
        provider:
          type: string
          enum:
            - mercadopago
            - mercadopago_livre
        brand:
          type: string
          example: visa
        installments:
          type: integer
          example: 1
    DetailsPix:
      description: response of details pix
      properties:
        provider:
          type: string
          enum:
            - bb
            - bs2
            - mercadopago
            - pagseguro
        qr_code:
          type: string
          example: 0000909br.gov.bcb.pix3243qrcodepix-h.bb.com.br/pix/v2/4123432423-234234-23432ebt
    DetailsBoleto:
      description: response of details boleto
      properties:
        provider:
          type: string
          enum:
            - bb
            - bs2
        due_date:
          type: string
          example: '2023-12-15T00:00:00.000Z'
        barcode:
          type: string
          example: '0019190740000001100019000009031285577'
        barcode_raw:
          type: string
          example: '001900000903128557700191907400000011'
    AuthenticationException:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: AuthenticationException
            message:
              type: string
              example: Unauthenticated.
    PaymentMethodNotSupportedException:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: PaymentMethodNotSupportedException
            message:
              type: string
              example: Payment method not supported
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
